# Generated by Django 4.1.4 on 2022-12-24 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('balance', models.DecimalField(decimal_places=3, max_digits=7, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reciept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=200)),
                ('total_before_tax', models.DecimalField(decimal_places=10, max_digits=19, null=True)),
                ('tax', models.DecimalField(decimal_places=10, max_digits=19, null=True)),
                ('tip', models.DecimalField(decimal_places=10, max_digits=19, null=True)),
                ('total', models.DecimalField(decimal_places=10, max_digits=19, null=True)),
                ('tax_percent', models.DecimalField(decimal_places=10, max_digits=19, null=True)),
                ('tip_percent', models.DecimalField(decimal_places=10, max_digits=19, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Split',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bill.item')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bill.person')),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='items',
            field=models.ManyToManyField(through='bill.Split', to='bill.item'),
        ),
        migrations.AddField(
            model_name='person',
            name='reciept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bill.reciept'),
        ),
        migrations.AddField(
            model_name='item',
            name='persons',
            field=models.ManyToManyField(through='bill.Split', to='bill.person'),
        ),
    ]
